"""Translated content for the public information and legal pages."""

PUBLIC_PAGES = {
    "pt-br": {
        "about": {"kicker":"Nossa história", "title":"Transporte público mais simples, cidade por cidade", "intro":"O Meu Busão transforma dados abertos de mobilidade em rotas, paradas, mapas e horários fáceis de entender.", "sections":[("Por que existimos","Esperar um ônibus não deveria ser um exercício de adivinhação. Criamos o Meu Busão para reunir informações dispersas e ajudar passageiros a tomar decisões com mais confiança."),("Como trabalhamos","Usamos dados GTFS publicados por agências de transporte e os apresentamos em uma experiência clara, rápida e gratuita. A disponibilidade depende da qualidade e atualização dos dados de cada cidade."),("Uma iniciativa independente","O projeto é mantido por uma pequena equipe e pela comunidade. Não somos uma operadora de transporte; somos uma ponte entre dados públicos e quem precisa se deslocar.")]},
        "faq": {"kicker":"Central de ajuda", "title":"Perguntas frequentes", "intro":"Respostas rápidas sobre horários, dados, mapas e privacidade.", "items":[("Os horários são em tempo real?","Quando a agência fornece dados em tempo real, podemos apresentá-los. Caso contrário, mostramos os horários planejados do feed GTFS."),("Por que uma linha ou parada não aparece?","A cobertura depende dos dados publicados pela agência local. Use a página de contato para informar dados ausentes ou incorretos."),("O serviço é gratuito?","Sim. O acesso ao site e às informações de transporte é gratuito."),("Como encontro os ônibus de uma parada?","Abra uma cidade e toque em uma parada no mapa. O painel inferior mostrará as linhas e próximas partidas disponíveis."),("Como usar ‘Como chegar’?","Na ficha da parada, escolha Como chegar e autorize sua localização. Uma rota de transporte público será aberta até o ponto escolhido."),("Quais dados pessoais são usados?","Usamos apenas o necessário para operar o site e respeitamos suas escolhas de consentimento. Consulte a Política de Privacidade.")]},
        "contact": {"kicker":"Fale conosco", "title":"Vamos melhorar a mobilidade juntos", "intro":"Encontrou dados incorretos, quer incluir uma cidade ou colaborar? Envie uma mensagem.", "email_label":"E-mail", "location_label":"Localização", "location":"Grenoble, França", "topics":"Podemos ajudar com", "topic_list":["Correções de linhas e paradas","Novas cidades e fontes GTFS","Traduções e acessibilidade","Parcerias e colaboração"], "button":"Enviar e-mail"},
        "terms": {"kicker":"Informações legais", "title":"Termos e Condições", "intro":"Regras para utilizar o site, aplicativo e serviços Meu Busão.", "updated":"Atualizado em 2 de agosto de 2026", "sections":[("1. Aceitação","Ao acessar o Meu Busão, você concorda com estes termos e com nossa Política de Privacidade. Se não concordar, não utilize o serviço."),("2. Informações de transporte","Rotas, paradas e horários vêm de fontes públicas ou terceiros. Trabalhamos para apresentar dados corretos, mas não garantimos disponibilidade, pontualidade ou ausência de erros. Confirme informações críticas com a operadora local."),("3. Uso permitido","Você pode usar o serviço para fins pessoais e legítimos. Não tente interromper a plataforma, contornar medidas de segurança, extrair dados de forma abusiva ou utilizá-la para atividades ilegais."),("4. Propriedade intelectual","A marca, o design e o software do Meu Busão são protegidos. Dados de transporte e mapas permanecem sujeitos às licenças de seus respectivos fornecedores."),("5. Serviços de terceiros","Mapas, direções e links externos podem ser fornecidos por terceiros e estão sujeitos aos seus próprios termos e políticas."),("6. Limitação de responsabilidade","O serviço é oferecido como está. Na medida permitida por lei, não respondemos por perdas decorrentes de atrasos, alterações de serviço, dados incorretos ou indisponibilidade."),("7. Alterações","Podemos atualizar estes termos. A versão publicada nesta página é a versão vigente."),("8. Contato","Dúvidas sobre estes termos podem ser enviadas para locoselli2016@gmail.com.")]},
        "privacy": {"kicker":"Sua privacidade", "title":"Política de Privacidade", "intro":"Como tratamos dados e protegemos suas escolhas ao usar o Meu Busão.", "updated":"Atualizado em 2 de agosto de 2026", "sections":[("1. Responsável","Meu Busão é uma iniciativa independente sediada em Grenoble, França. Para assuntos de privacidade: locoselli2016@gmail.com."),("2. Dados tratados","Podemos tratar endereço IP, informações técnicas do navegador, idioma escolhido, preferências de consentimento e dados de uso necessários à segurança e ao funcionamento. A localização é solicitada apenas quando você escolhe Como chegar e é enviada diretamente ao serviço de mapas selecionado."),("3. Finalidades e bases legais","Usamos dados para entregar o serviço, manter segurança, lembrar preferências e cumprir obrigações legais. Quando necessário, o tratamento se baseia em consentimento, interesse legítimo, execução do serviço ou obrigação legal."),("4. Cookies e armazenamento","O armazenamento essencial mantém idioma, sessão e escolha de privacidade. Recursos opcionais dependem do seu consentimento. Você pode alterar a decisão a qualquer momento pelo link Cookies no rodapé."),("5. Compartilhamento","Não vendemos dados pessoais. Podemos utilizar provedores de hospedagem, mapas e segurança, ou responder a autoridades quando exigido por lei."),("6. Conservação e segurança","Mantemos dados somente pelo tempo necessário e aplicamos medidas razoáveis de proteção. Nenhum sistema conectado à internet é totalmente livre de riscos."),("7. Transferências internacionais","Alguns fornecedores podem processar dados fora do seu país. Quando aplicável, utilizamos salvaguardas previstas em lei."),("8. Seus direitos","Conforme RGPD, LGPD e legislação aplicável, você pode solicitar acesso, correção, exclusão, limitação, portabilidade, oposição ou retirada do consentimento."),("9. Crianças","O serviço não é direcionado a crianças menores de 13 anos. Entre em contato se acreditar que uma criança forneceu dados pessoais."),("10. Contato e reclamações","Envie solicitações para locoselli2016@gmail.com. Você também pode reclamar à autoridade de proteção de dados competente.")]},
    },
}

# Compact, professionally translated equivalents. Structure intentionally
# matches PT-BR so the same accessible templates render every language.
PUBLIC_PAGES["fr"] = {
 "about":{"kicker":"Notre histoire","title":"Des transports publics plus simples, ville après ville","intro":"Meu Busão transforme les données ouvertes de mobilité en lignes, arrêts, cartes et horaires faciles à comprendre.","sections":[("Notre raison d’être","Attendre un bus ne devrait pas relever du hasard. Nous réunissons des informations dispersées pour aider chaque voyageur à décider sereinement."),("Notre méthode","Nous utilisons les données GTFS des autorités de transport et les présentons dans une expérience claire, rapide et gratuite. Leur disponibilité dépend de chaque ville."),("Une initiative indépendante","Une petite équipe et la communauté maintiennent le projet. Nous ne sommes pas un opérateur, mais un lien entre les données publiques et les voyageurs.")]},
 "faq":{"kicker":"Centre d’aide","title":"Questions fréquentes","intro":"Réponses sur les horaires, données, cartes et confidentialité.","items":[("Les horaires sont-ils en temps réel ?","Lorsque l’autorité fournit du temps réel, nous pouvons l’afficher. Sinon, nous présentons les horaires planifiés GTFS."),("Pourquoi une ligne manque-t-elle ?","La couverture dépend des données locales. Signalez toute donnée absente ou incorrecte depuis la page Contact."),("Le service est-il gratuit ?","Oui, l’accès au site et aux informations est gratuit."),("Quels bus desservent un arrêt ?","Touchez un arrêt sur la carte pour afficher ses lignes et prochains départs."),("Comment utiliser l’itinéraire ?","Dans la fiche d’un arrêt, choisissez Comment s’y rendre et autorisez votre position."),("Quelles données personnelles utilisez-vous ?","Uniquement ce qui est nécessaire au service, selon vos choix de consentement. Consultez notre Politique de confidentialité.")]},
 "contact":{"kicker":"Nous contacter","title":"Améliorons la mobilité ensemble","intro":"Une erreur, une nouvelle ville ou une idée de collaboration ? Écrivez-nous.","email_label":"E-mail","location_label":"Localisation","location":"Grenoble, France","topics":"Nous pouvons vous aider","topic_list":["Corrections de lignes et d’arrêts","Nouvelles villes et sources GTFS","Traduction et accessibilité","Partenariats et collaboration"],"button":"Envoyer un e-mail"},
 "terms":{"kicker":"Informations légales","title":"Conditions générales","intro":"Les règles d’utilisation du site, de l’application et des services Meu Busão.","updated":"Mis à jour le 2 août 2026","sections":[("1. Acceptation","En utilisant Meu Busão, vous acceptez ces conditions et notre Politique de confidentialité."),("2. Informations de transport","Les données proviennent de sources publiques ou tierces. Nous ne garantissons ni ponctualité, ni disponibilité, ni absence d’erreur."),("3. Utilisation autorisée","Utilisez le service à des fins personnelles et légitimes, sans perturber la plateforme ni contourner sa sécurité."),("4. Propriété intellectuelle","La marque, le design et le logiciel sont protégés. Les données et cartes restent soumises aux licences de leurs fournisseurs."),("5. Services tiers","Les cartes, itinéraires et liens externes sont régis par les conditions de leurs fournisseurs."),("6. Responsabilité","Le service est fourni en l’état. Dans les limites légales, nous ne répondons pas des retards, modifications ou erreurs de données."),("7. Modifications","La version publiée sur cette page est la version en vigueur."),("8. Contact","Écrivez à locoselli2016@gmail.com pour toute question.")]},
 "privacy":{"kicker":"Votre vie privée","title":"Politique de confidentialité","intro":"Comment nous traitons les données et respectons vos choix.","updated":"Mis à jour le 2 août 2026","sections":[("1. Responsable","Meu Busão est une initiative indépendante basée à Grenoble. Contact : locoselli2016@gmail.com."),("2. Données traitées","Adresse IP, navigateur, langue, consentement et données techniques nécessaires. La position n’est demandée que pour créer un itinéraire."),("3. Finalités et bases","Nous traitons les données pour fournir et sécuriser le service, mémoriser vos choix et respecter la loi."),("4. Cookies","Le stockage essentiel conserve langue, session et consentement. Modifiez vos choix via Cookies dans le pied de page."),("5. Partage","Nous ne vendons pas vos données. Des prestataires d’hébergement, cartes et sécurité peuvent intervenir."),("6. Conservation et sécurité","Les données sont conservées uniquement le temps nécessaire avec des mesures de protection raisonnables."),("7. Transferts","Des garanties légales sont appliquées aux traitements internationaux lorsque nécessaire."),("8. Vos droits","Vous pouvez demander accès, correction, effacement, limitation, portabilité, opposition ou retrait du consentement."),("9. Enfants","Le service ne s’adresse pas aux enfants de moins de 13 ans."),("10. Contact","Écrivez à locoselli2016@gmail.com ou contactez votre autorité de protection des données.")]},
}

PUBLIC_PAGES["it"] = {
 "about":{"kicker":"La nostra storia","title":"Trasporto pubblico più semplice, città dopo città","intro":"Meu Busão trasforma dati aperti sulla mobilità in linee, fermate, mappe e orari chiari.","sections":[("Perché esistiamo","Aspettare un autobus non dovrebbe essere un’incognita. Riuniamo informazioni disperse per aiutare i passeggeri a scegliere con sicurezza."),("Come lavoriamo","Utilizziamo dati GTFS delle aziende di trasporto in un’esperienza chiara, veloce e gratuita. La disponibilità dipende da ogni città."),("Un’iniziativa indipendente","Il progetto è gestito da un piccolo team e dalla comunità. Siamo un ponte tra dati pubblici e passeggeri.")]},
 "faq":{"kicker":"Centro assistenza","title":"Domande frequenti","intro":"Risposte su orari, dati, mappe e privacy.","items":[("Gli orari sono in tempo reale?","Quando disponibili mostriamo dati in tempo reale; altrimenti gli orari programmati GTFS."),("Perché manca una linea?","La copertura dipende dai dati locali. Segnala errori dalla pagina Contatti."),("Il servizio è gratuito?","Sì, il sito e le informazioni sono gratuiti."),("Quali bus passano da una fermata?","Tocca una fermata sulla mappa per vedere linee e prossime partenze."),("Come uso Come arrivare?","Apri la scheda della fermata, scegli Come arrivare e autorizza la posizione."),("Quali dati personali usate?","Solo quelli necessari, secondo le tue scelte. Consulta la Privacy Policy.")]},
 "contact":{"kicker":"Contattaci","title":"Miglioriamo insieme la mobilità","intro":"Dati errati, una nuova città o una collaborazione? Scrivici.","email_label":"E-mail","location_label":"Sede","location":"Grenoble, Francia","topics":"Possiamo aiutarti con","topic_list":["Correzioni di linee e fermate","Nuove città e fonti GTFS","Traduzioni e accessibilità","Partnership e collaborazione"],"button":"Invia e-mail"},
 "terms":{"kicker":"Informazioni legali","title":"Termini e condizioni","intro":"Regole di utilizzo del sito, dell’app e dei servizi Meu Busão.","updated":"Aggiornato il 2 agosto 2026","sections":[("1. Accettazione","Usando Meu Busão accetti questi termini e la Privacy Policy."),("2. Informazioni di trasporto","I dati provengono da fonti pubbliche o terze; non garantiamo puntualità, disponibilità o assenza di errori."),("3. Uso consentito","Usa il servizio per scopi personali e leciti senza interrompere la piattaforma o aggirarne la sicurezza."),("4. Proprietà intellettuale","Marchio, design e software sono protetti; dati e mappe seguono le licenze dei fornitori."),("5. Servizi terzi","Mappe, indicazioni e link esterni seguono i termini dei rispettivi fornitori."),("6. Responsabilità","Il servizio è fornito così com’è. Nei limiti di legge non rispondiamo di ritardi, modifiche o dati errati."),("7. Modifiche","La versione pubblicata su questa pagina è quella vigente."),("8. Contatti","Scrivi a locoselli2016@gmail.com.")]},
 "privacy":{"kicker":"La tua privacy","title":"Informativa sulla privacy","intro":"Come trattiamo i dati e proteggiamo le tue scelte.","updated":"Aggiornato il 2 agosto 2026","sections":[("1. Titolare","Meu Busão è un’iniziativa indipendente con sede a Grenoble. Contatto: locoselli2016@gmail.com."),("2. Dati trattati","IP, browser, lingua, consenso e dati tecnici necessari. La posizione è richiesta solo per creare un percorso."),("3. Finalità e basi","Trattiamo dati per fornire e proteggere il servizio, ricordare le preferenze e rispettare la legge."),("4. Cookie","Lo storage essenziale conserva lingua, sessione e consenso. Cambia scelta dal link Cookie nel footer."),("5. Condivisione","Non vendiamo dati. Possiamo usare fornitori di hosting, mappe e sicurezza."),("6. Conservazione e sicurezza","Conserviamo i dati solo per il tempo necessario con misure ragionevoli."),("7. Trasferimenti","Quando richiesto applichiamo garanzie ai trasferimenti internazionali."),("8. Diritti","Puoi chiedere accesso, rettifica, cancellazione, limitazione, portabilità, opposizione o revoca."),("9. Minori","Il servizio non è rivolto a minori di 13 anni."),("10. Contatti","Scrivi a locoselli2016@gmail.com o alla tua autorità competente.")]},
}

PUBLIC_PAGES["es"] = {
 "about":{"kicker":"Nuestra historia","title":"Transporte público más sencillo, ciudad por ciudad","intro":"Meu Busão convierte datos abiertos de movilidad en líneas, paradas, mapas y horarios fáciles de entender.","sections":[("Por qué existimos","Esperar un autobús no debería ser una adivinanza. Reunimos información dispersa para ayudar a viajar con confianza."),("Cómo trabajamos","Utilizamos datos GTFS de agencias de transporte y los presentamos de forma clara, rápida y gratuita."),("Una iniciativa independiente","Un pequeño equipo y la comunidad mantienen el proyecto. Somos un puente entre los datos públicos y los pasajeros.")]},
 "faq":{"kicker":"Centro de ayuda","title":"Preguntas frecuentes","intro":"Respuestas sobre horarios, datos, mapas y privacidad.","items":[("¿Los horarios son en tiempo real?","Cuando están disponibles mostramos datos en vivo; de lo contrario, horarios GTFS planificados."),("¿Por qué falta una línea?","La cobertura depende de los datos locales. Informa errores desde Contacto."),("¿El servicio es gratuito?","Sí, el acceso al sitio y a la información es gratuito."),("¿Qué autobuses pasan por una parada?","Toca una parada en el mapa para ver líneas y próximas salidas."),("¿Cómo uso Cómo llegar?","Abre la ficha de la parada, selecciona Cómo llegar y autoriza la ubicación."),("¿Qué datos personales utilizan?","Solo los necesarios según tus elecciones. Consulta nuestra Política de Privacidad.")]},
 "contact":{"kicker":"Contacto","title":"Mejoremos juntos la movilidad","intro":"¿Datos incorrectos, una nueva ciudad o una colaboración? Escríbenos.","email_label":"Correo electrónico","location_label":"Ubicación","location":"Grenoble, Francia","topics":"Podemos ayudarte con","topic_list":["Correcciones de líneas y paradas","Nuevas ciudades y fuentes GTFS","Traducción y accesibilidad","Alianzas y colaboración"],"button":"Enviar correo"},
 "terms":{"kicker":"Información legal","title":"Términos y condiciones","intro":"Reglas para utilizar el sitio, la aplicación y los servicios Meu Busão.","updated":"Actualizado el 2 de agosto de 2026","sections":[("1. Aceptación","Al usar Meu Busão aceptas estos términos y nuestra Política de Privacidad."),("2. Información de transporte","Los datos proceden de fuentes públicas o terceros; no garantizamos puntualidad, disponibilidad ni ausencia de errores."),("3. Uso permitido","Usa el servicio con fines personales y legales, sin interrumpirlo ni eludir su seguridad."),("4. Propiedad intelectual","La marca, diseño y software están protegidos; los datos y mapas conservan sus propias licencias."),("5. Terceros","Mapas, indicaciones y enlaces externos se rigen por las condiciones de sus proveedores."),("6. Responsabilidad","El servicio se ofrece tal cual. Dentro de la ley no respondemos por retrasos, cambios o datos incorrectos."),("7. Cambios","La versión publicada en esta página es la vigente."),("8. Contacto","Escribe a locoselli2016@gmail.com.")]},
 "privacy":{"kicker":"Tu privacidad","title":"Política de privacidad","intro":"Cómo tratamos los datos y protegemos tus decisiones.","updated":"Actualizado el 2 de agosto de 2026","sections":[("1. Responsable","Meu Busão es una iniciativa independiente en Grenoble. Contacto: locoselli2016@gmail.com."),("2. Datos tratados","IP, navegador, idioma, consentimiento y datos técnicos. La ubicación solo se solicita para crear una ruta."),("3. Finalidad y bases","Tratamos datos para prestar y proteger el servicio, recordar preferencias y cumplir la ley."),("4. Cookies","El almacenamiento esencial conserva idioma, sesión y consentimiento. Cambia tus opciones desde Cookies en el pie."),("5. Compartir datos","No vendemos datos. Podemos usar proveedores de alojamiento, mapas y seguridad."),("6. Conservación y seguridad","Conservamos datos solo el tiempo necesario y aplicamos medidas razonables."),("7. Transferencias","Aplicamos garantías legales a transferencias internacionales cuando corresponde."),("8. Derechos","Puedes solicitar acceso, rectificación, supresión, limitación, portabilidad, oposición o retirar el consentimiento."),("9. Menores","El servicio no está dirigido a menores de 13 años."),("10. Contacto","Escribe a locoselli2016@gmail.com o a tu autoridad de protección de datos.")]},
}

PUBLIC_PAGES["pt-br"]["privacy"]["sections"].append(("11. Favoritos locais", "As linhas favoritas do Meu espaço são armazenadas no localStorage do seu navegador. Elas não são enviadas à nossa conta ou sincronizadas. Você pode removê-las individualmente ou apagar os dados do site no navegador."))
PUBLIC_PAGES["fr"]["privacy"]["sections"].append(("11. Favoris locaux", "Les lignes de Mon espace sont conservées dans le stockage local du navigateur. Elles ne sont ni envoyées à un compte ni synchronisées. Vous pouvez les retirer ou effacer les données du site."))
PUBLIC_PAGES["it"]["privacy"]["sections"].append(("11. Preferiti locali", "Le linee del Mio spazio sono conservate nel localStorage del browser. Non vengono inviate a un account né sincronizzate. Puoi rimuoverle o cancellare i dati del sito."))
PUBLIC_PAGES["es"]["privacy"]["sections"].append(("11. Favoritos locales", "Las líneas de Mi espacio se guardan en el almacenamiento local del navegador. No se envían a una cuenta ni se sincronizan. Puedes eliminarlas o borrar los datos del sitio."))

# Keep the Google Play app, developer, and legal-operator identifiers explicit
# and consistent in every localized version of the policy.
PRIVACY_APP_IDENTITY = {
    "pt-br": {
        "title": "Política de Privacidade — Bus - Monopoli",
        "intro": "Como tratamos dados e protegemos suas escolhas ao usar os aplicativos Bus - Monopoli e Mon Bus - Grenoble - Tag.",
        "updated": "Atualizado em 12 de agosto de 2026",
        "section": ("1. Aplicativos, desenvolvedor e responsável legal", "Esta Política de Privacidade se aplica aos aplicativos Bus - Monopoli e Mon Bus - Grenoble - Tag, ambos publicados no Google Play com o nome de desenvolvedor Rodrigo Locoselli. A pessoa física responsável legal, operadora dos aplicativos e controladora de dados é Rodrigo Locoselli Gutierres, situada em 16 Rue Nicolas Chorier, 38000 Grenoble, França. Contato: locoselli2016@gmail.com."),
    },
    "fr": {
        "title": "Politique de confidentialité — Bus - Monopoli",
        "intro": "Comment nous traitons les données lors de l’utilisation des applications Bus - Monopoli et Mon Bus - Grenoble - Tag.",
        "updated": "Mis à jour le 12 août 2026",
        "section": ("1. Applications, développeur et responsable légal", "Cette politique s’applique aux applications Bus - Monopoli et Mon Bus - Grenoble - Tag, toutes deux publiées sur Google Play sous le nom de développeur Rodrigo Locoselli. La personne physique juridiquement responsable, exploitant les applications et responsable du traitement est Rodrigo Locoselli Gutierres, située au 16 Rue Nicolas Chorier, 38000 Grenoble, France. Contact : locoselli2016@gmail.com."),
    },
    "it": {
        "title": "Informativa sulla privacy — Bus - Monopoli",
        "intro": "Come trattiamo i dati durante l’uso delle app Bus - Monopoli e Mon Bus - Grenoble - Tag.",
        "updated": "Aggiornato il 12 agosto 2026",
        "section": ("1. App, sviluppatore e responsabile legale", "Questa informativa si applica alle app Bus - Monopoli e Mon Bus - Grenoble - Tag, entrambe pubblicate su Google Play con il nome sviluppatore Rodrigo Locoselli. La persona fisica legalmente responsabile, gestore delle app e titolare del trattamento è Rodrigo Locoselli Gutierres, con sede in 16 Rue Nicolas Chorier, 38000 Grenoble, Francia. Contatto: locoselli2016@gmail.com."),
    },
    "es": {
        "title": "Política de privacidad — Bus - Monopoli",
        "intro": "Cómo tratamos los datos al utilizar las aplicaciones Bus - Monopoli y Mon Bus - Grenoble - Tag.",
        "updated": "Actualizado el 12 de agosto de 2026",
        "section": ("1. Aplicaciones, desarrollador y responsable legal", "Esta política se aplica a las aplicaciones Bus - Monopoli y Mon Bus - Grenoble - Tag, ambas publicadas en Google Play con el nombre de desarrollador Rodrigo Locoselli. La persona física legalmente responsable, operadora de las aplicaciones y responsable del tratamiento es Rodrigo Locoselli Gutierres, ubicada en 16 Rue Nicolas Chorier, 38000 Grenoble, Francia. Contacto: locoselli2016@gmail.com."),
    },
}

for locale, identity in PRIVACY_APP_IDENTITY.items():
    policy = PUBLIC_PAGES[locale]["privacy"]
    policy.update({key: identity[key] for key in ("title", "intro", "updated")})
    policy["sections"][0] = identity["section"]
